name: resnet_coral_pt_nfr

backbone: efficientnet_b0
pretrained: true
freeze_backbone: false

head: coral # regression | dldl | hybrid | coral
num_classes: 117

loss:
  name: coral

optimizer:
  name: adam
  lr: 1e-4
