name: resnet_50_cemv_pt_ft_34_cos
checkpoint_name: resnet_50_cemv_pt_ft_34_cos.pth
backbone: resnet50
pretrained: true
freeze_backbone: true
head: classification
num_classes: 117

loss:
  name: ce_mv
  lambda_mean: 0.2
  lambda_var: 0.05

optimizer:
  name: adamw
  lr: 5e-4
  weight_decay: 1e-4

scheduler:
  name: cosine
  T_max: 20
  eta_min: 1e-6
  interval: epoch

finetune:
  enabled: true
  unfreeze_epoch: 0
  backbone_lr: 1e-5
  unfreeze_layers: ["layer4", "layer3"] # layer4 + layer3
