name: resnet_18_cemv_pt_ft
checkpoint_name: resnet_18_cemv_pt_ft.pth

backbone: resnet18
pretrained: true
freeze_backbone: true

head: classification
num_classes: 117

loss:
  name: ce_mv
  lambda_mean: 0.2
  lambda_var: 0.05

optimizer:
  name: adamw
  lr: 5e-4
  weight_decay: 1e-4

finetune:
  enabled: true
  unfreeze_epoch: 0
  backbone_lr: 3e-4
